import localFont from "next/font/local";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import { AuthProvider } from "@/hooks/AuthProvider";
import CustomNavbar from "@/ui/CustomNavbar";
import { UserProvider } from "@/contexts/UserContext";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-200`}
      >
        <AuthProvider>
          <UserProvider>

          <CustomNavbar />
          {children}
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
